[package]
name = "zksync_server"
version = "1.0.0"
edition = "2018"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/zksync"
license = "Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]
publish = false # We don't want to publish our binaries.

[dependencies]
zksync_api = { path = "../zksync_api", version = "1.0" }
zksync_core = { path = "../zksync_core", version = "1.0" }
zksync_witness_generator = { path = "../zksync_witness_generator", version = "1.0" }
zksync_eth_sender = { path = "../zksync_eth_sender", version = "1.0" }
zksync_prometheus_exporter = { path = "../zksync_prometheus_exporter", version = "1.0" }

zksync_config = { path = "../../lib/config", version = "1.0" }
zksync_storage = { path = "../../lib/storage", version = "1.0" }

anyhow = "1.0"
structopt = "0.3.20"
log = "0.4"
env_logger = "0.6"
ctrlc = { version = "3.1", features = ["termination"] }
futures = "0.3"
tokio = { version = "0.2", features = ["full"] }

[dev-dependencies]
zksync_crypto = { path = "../../lib/crypto", version = "1.0" }
zksync_types = { path = "../../lib/types", version = "1.0" }
zksync_prover = { path = "../prover", version = "1.0" }
zksync_utils = { path = "../../lib/utils", version = "1.0" }

num = { version = "0.2", features = ["serde"] }
serde = "1.0.90"
serde_json = "1.0.0"
