[workspace]
members = [
    # Binaries
    "core/bin/data_restore",
    "core/bin/key_generator",
    "core/bin/server",
    "core/bin/prover",
    "core/bin/gen_token_add_contract",
    "core/bin/parse_pub_data",

    # Server micro-services
    "core/bin/zksync_api",
    "core/bin/zksync_core",
    "core/bin/zksync_eth_sender",
    "core/bin/zksync_witness_generator",
    "core/bin/zksync_prometheus_exporter",

    # Libraries
    "core/lib/circuit",
    "core/lib/eth_client",
    "core/lib/eth_signer",
    "core/lib/types",
    "core/lib/state",
    "core/lib/storage",
    "core/lib/vlog",
    "core/lib/crypto",
    "core/lib/utils",
    "core/lib/basic_types",
    "core/lib/prover_utils",
    "core/lib/config",
    "core/lib/contracts",

    # Test infrastructure
    "core/tests/test_account",
    "core/tests/testkit",
    "core/tests/loadtest",

    # Infrastructure applications
    "infrastructure/tok_cli",

    # SDK section
    "sdk/zksync-rs",
]
